namespace: vexxhost
name: containers
version: 1.2.1 # x-release-please-version
readme: README.md
authors:
  - Mohammed Naser <mnaser@vexxhost.com>
description: Ansible collection for deploying container runtimes
license:
  - GPL-3.0-or-later
dependencies:
  ansible.posix: ">=1.3.0"
  community.general: ">=4.5.0"
tags:
  - application
  - cloud
  - infrastructure
  - linux
repository: https://github.com/vexxhost/ansible-collection-containers
documentation: https://github.com/vexxhost/ansible-collection-containers/tree/main/docs
homepage: https://github.com/vexxhost/ansible-collection-containers
issues: https://github.com/vexxhost/ansible-collection-containers/issues
build_ignore:
  - .github
  - molecule
  - .pre-commit-config.yaml
  - .release-please-manifest.json
  - release-please-config.json
