# Copyright (c) 2026 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

docker_versions: "{{ docker_archive_checksums['amd64'].keys() | list | community.general.version_sort }}"
docker_version: "{{ docker_versions | last }}"

docker_archive_checksums:
  amd64:
    24.0.9: 692ecfc28333485d184f628b74c25b2894cee9495a51a5418ba60ef95bf733ca
    29.7.2: 803d433f226db4776e1768fd319fc6c6e4935a456acf84fcc0080818b854bc8f
  arm64:
    24.0.9: 7e999590330a15469de20ac37051407d222ea73c71c10c05d61666d42c5922d1
    29.7.2: 43d143448adf2c2787704e7d7704fd6d62d367a54c5edaef0a3f75509cb0938d

docker_download_url: "https://download.docker.com/linux/static/stable/{{ ansible_facts['architecture'] | lower }}/docker-{{ docker_version }}.tgz" # noqa: yaml[line-length]

docker_download_dest: "{{ download_artifact_work_directory }}/docker-{{ docker_version }}.tgz"
docker_archive_checksum: "{{ docker_archive_checksums[download_artifact_goarch][docker_version] }}"
docker_binary_install_dir: "{{ download_artifact_work_directory }}/docker-{{ docker_version }}"
docker_binaries:
  - docker
  - docker-init
  - dockerd
  - docker-proxy

# Updating the installed binaries and configuration does not require activating
# them immediately. Service or node restarts can be performed separately as
# part of a controlled maintenance operation.
docker_restart_on_update: false

# NOTE(mnaser): This is to accomodate for the uninstallation of the old packages
#               that shipped with the operating system
docker_package_name: docker-ce
docker_cfg_dir: /etc/docker
docker_cfg_file: "{{ docker_cfg_dir }}/daemon.json"
docker_storage_dir: /var/lib/docker
docker_state_dir: /run/docker

docker_http_proxy: "{{ http_proxy | default('') }}"
docker_https_proxy: "{{ https_proxy | default('') }}"
docker_no_proxy: "{{ no_proxy | default('') }}"

docker_config: {}
