# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all
  become: true
  pre_tasks:
    - name: Populate package facts
      ansible.builtin.package_facts:

    - name: Populate service facts
      ansible.builtin.service_facts:

  tasks:
    - name: Assert that the NGINX package is not installed
      ansible.builtin.assert:
        that:
          - '"nginx" not in ansible_facts.packages'

    - name: Assert that the NGINX service is still up
      ansible.builtin.assert:
        that:
          - ansible_facts.services["nginx.service"].state == "running"
          - ansible_facts.services["nginx.service"].status == "enabled"
