# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "quay.io/gotmax23/${MOLECULE_DISTRO_ID:-debian}-systemd:${MOLECULE_DISTRO_VERSION_ID:-bookworm}"
    pre_build_image: true
    override_command: false
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /sys/fs/cgroup/systemd
      - /var/lib/journal
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    connection:
      pipelining: true
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
verifier:
  name: ansible
