# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all
  roles:
    - vexxhost.containers.nerdctl
  post_tasks:
    - name: Install the 10-containerd-net.conflist file
      ansible.builtin.copy:
        dest: /etc/cni/net.d/10-containerd-net.conflist
        content: |
          {
            "cniVersion": "1.0.0",
            "name": "containerd-net",
            "plugins": [
              {
                "type": "bridge",
                "bridge": "cni0",
                "isGateway": true,
                "ipMasq": true,
                "promiscMode": true,
                "ipam": {
                  "type": "host-local",
                  "ranges": [
                    [{
                      "subnet": "10.88.0.0/16"
                    }],
                    [{
                      "subnet": "2001:4860:4860::/64"
                    }]
                  ],
                  "routes": [
                    { "dst": "0.0.0.0/0" },
                    { "dst": "::/0" }
                  ]
                }
              },
              {
                "type": "portmap",
                "capabilities": {"portMappings": true}
              }
            ]
          }

    - name: Restart "containerd"
      ansible.builtin.service:
        name: containerd
        state: restarted

    - name: Pull image from registry
      ansible.builtin.command: nerdctl image pull docker.io/library/alpine:latest

    - name: List images
      ansible.builtin.command: nerdctl image ls
      register: images
      failed_when: not(images.stdout.find('alpine') != -1)
