# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all
  become: true
  roles:
    - vexxhost.containers.cni_plugins
    - vexxhost.containers.cri_tools
  post_tasks:
    - name: Install the 10-containerd-net.conflist file
      ansible.builtin.copy:
        dest: /etc/cni/net.d/10-containerd-net.conflist
        content: |
          {
            "cniVersion": "1.0.0",
            "name": "containerd-net",
            "plugins": [
              {
                "type": "bridge",
                "bridge": "cni0",
                "isGateway": true,
                "ipMasq": true,
                "promiscMode": true,
                "ipam": {
                  "type": "host-local",
                  "ranges": [
                    [{
                      "subnet": "10.88.0.0/16"
                    }],
                    [{
                      "subnet": "2001:4860:4860::/64"
                    }]
                  ],
                  "routes": [
                    { "dst": "0.0.0.0/0" },
                    { "dst": "::/0" }
                  ]
                }
              },
              {
                "type": "portmap",
                "capabilities": {"portMappings": true}
              }
            ]
          }

    - name: Restart "containerd"
      ansible.builtin.service:
        name: containerd
        state: restarted

    - name: Run test suite
      block:
        - name: Run "critest"
          ansible.builtin.command: critest
          register: _critest
      always:
        - name: Print out "critest" output
          ansible.builtin.debug:
            msg: "{{ _critest.stdout_lines }}"
