# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: boxen/${MOLECULE_VAGRANT_BOX:-debian-13}
    cpu: 2
    memory: 8192
    provider_raw_config_args:
      - loader = "/usr/share/OVMF/OVMF_CODE_4M.fd"
      - nvram = "/var/lib/libvirt/qemu/nvram/OVMF_VARS_4M.fd"
      - cpu_mode = 'host-passthrough'
      - disk_bus = 'virtio'
      - nic_model_type = 'virtio'
      - video_type = 'virtio'
      - disk_driver :cache => 'writeback'
      - "storage :file, bus: 'virtio', cache: 'writeback'"
    instance_raw_config_args:
      - vm.box_check_update = false
provisioner:
  name: ansible
  config_options:
    connection:
      pipelining: true
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    host_vars:
      instance:
        ansible_become: true
        docker_version: 24.0.9
verifier:
  name: ansible
