# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all
  become: true
  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

  tasks:
    - name: Assert that the Docker service is still up
      ansible.builtin.assert:
        that:
          - ansible_facts.services["docker.service"].state == "running"

    - name: Check if Docker version is correct
      command: docker --version
      register: version_output
      failed_when: "docker_version not in version_output.stdout"

    - name: Check if docker ps command return 0
      command: docker ps
      register: result
      failed_when: "result.rc !=0"
