# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Wait for user to read warning
  hosts: localhost
  tasks:
    - name: Wait for user to read warning
      ignore_errors: true # noqa: ignore-errors
      ansible.builtin.fail:
        msg: >-
          ⚠️
          This code will make substantial changes to your machine, it is strongly
          recommended that you run this on a server or virtual machine that you
          dedicate to this purpose.
          ⚠️

    - name: Wait for user to read warning
      ansible.builtin.wait_for:
        timeout: 15
