# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  ansible-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
      - run: uv run ansible-galaxy collection install .
      - run: uv run ansible-test units --python $(cat .python-version)
        working-directory: /home/runner/.ansible/collections/ansible_collections/vexxhost/containers
      - uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
        if: always()
        with:
          report_paths: /home/runner/.ansible/collections/ansible_collections/vexxhost/containers/tests/output/junit/*.xml

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian-13
          - rockylinux-9
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
        scenario:
          - containerd
          - docker
          - download-binaries
          - forget-package
          - nerdctl
        exclude:
          - distro: rockylinux9
            scenario: forget-package
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
      - name: vexxhost/setup-vagrant
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y --no-install-recommends ovmf dnsmasq-base qemu-kvm libvirt-dev libvirt-daemon-system ebtables vagrant ruby-fog-libvirt qemu-utils
          vagrant plugin install vagrant-libvirt
          sudo cp /usr/share/OVMF/OVMF_VARS_4M.fd /var/lib/libvirt/qemu/nvram/
      - run: sudo usermod -a -G libvirt $USER
      - shell: sg libvirt -c "bash -e {0}"
        run: |
          export MOLECULE_VAGRANT_BOX="${{ matrix.distro }}"
          uv run molecule test --destroy never -s "${{ matrix.scenario }}"
