name: pr

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1 # 1.5.2
        with:
          task_types: '["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test"]'
          add_label: 'false'
